{
  "formatVersion": "1.1",
  "component": {
    "group": "com.znh.page",
    "module": "hui_plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "hui_plugin-1.0.0.jar",
          "url": "hui_plugin-1.0.0.jar",
          "size": 9908,
          "sha512": "a065922caceda62fd8b8f218b9c2bcc7a0050f4fa213c5b7145f1f35db5b652dc8eb04c3babc29c3fe86b17114e9c407c9efa9f5d1636afa459f77f626705d04",
          "sha256": "f053fcf446bd724583fd8bd597eb1c07fb069e671c197eadd6478356210f0865",
          "sha1": "e67adb472cbc885f09759ba31b1e1ba03b4965a8",
          "md5": "fbb415f86b58d2c8a9510acf0e71b4d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "hui_plugin-1.0.0.jar",
          "url": "hui_plugin-1.0.0.jar",
          "size": 9908,
          "sha512": "a065922caceda62fd8b8f218b9c2bcc7a0050f4fa213c5b7145f1f35db5b652dc8eb04c3babc29c3fe86b17114e9c407c9efa9f5d1636afa459f77f626705d04",
          "sha256": "f053fcf446bd724583fd8bd597eb1c07fb069e671c197eadd6478356210f0865",
          "sha1": "e67adb472cbc885f09759ba31b1e1ba03b4965a8",
          "md5": "fbb415f86b58d2c8a9510acf0e71b4d0"
        }
      ]
    }
  ]
}
