{
  "formatVersion": "1.1",
  "component": {
    "group": "com.znh.plugin",
    "module": "hui_plugin",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "hui_plugin-1.0.1.jar",
          "url": "hui_plugin-1.0.1.jar",
          "size": 24137,
          "sha512": "4630bdf31cf18b5a83da361763d8a1aa1fa658d1c896d696b2ed5e57ec31a09a10e9d91c7f4f804b54eca948695b70c16450ff6b67a71feee2432e316f5cd83b",
          "sha256": "d3b5e01aab80cbd4326e9d1228a7fc5e16bd3f0644a39ed9f690784cc2f32cac",
          "sha1": "8aafdba104ed43874db7e0f072e8d7fcf7424703",
          "md5": "a22f33ef12c37174f21e877a70fadaf5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.1.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "hui_plugin-1.0.1.jar",
          "url": "hui_plugin-1.0.1.jar",
          "size": 24137,
          "sha512": "4630bdf31cf18b5a83da361763d8a1aa1fa658d1c896d696b2ed5e57ec31a09a10e9d91c7f4f804b54eca948695b70c16450ff6b67a71feee2432e316f5cd83b",
          "sha256": "d3b5e01aab80cbd4326e9d1228a7fc5e16bd3f0644a39ed9f690784cc2f32cac",
          "sha1": "8aafdba104ed43874db7e0f072e8d7fcf7424703",
          "md5": "a22f33ef12c37174f21e877a70fadaf5"
        }
      ]
    }
  ]
}
